baseURL: http://hugo-b-r.github.io/
title: Some random politic site
theme: PaperMod
paginate: 5
DefaultContentLanguage: fr

languages:
  fr:
    title: Des sortes d'idées...
    description: "Journal d'un jour"
    homeInfoParams:
      Title: "Des semblants d'idées..."
      Content: ""
    menu:
      main:
        - identifier : about
          name: A propos
          url: /about/
          weight: 20
  en:
    title: Some sorts of ideas...
    description: "One-day newspaper"
    homeInfoParams:
      Title: "Some sorts of ideas..."
      Content: ""
    menu:
      main:
        - identifier : about
          name: About 
          url: /about/
          weight: 20
  de:
    title: Ideen...
    description: ""
    homeInfoParams:
      Title: "Ideen..."
      Content: ""
    menu:
      main:
        - identifier : about
          name: Über
          url: /about/
          weight: 20


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  keywords: [Blog, Portfolio, PaperMod]
  author: Hugo Berthet-Rambaud
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  
  socialIcons:
    - name: github
      url: "https://github.com/hugo-b-r"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/hugo-b-r/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content", "tag"]


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai