# Deploy site to GitHub Pages on commit to master branch.
name: github-pages-deploy

on:
  # Triggers the workflow on push events but only to the master branch.
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE,
      # so the job can access it.
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.2'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          cname: everythingisgray.com
          commit_message: ${{ github.event.head_commit.message }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: hugo-b-r/hugo-b-r.github.io
          # Allows you to make your publish branch only
          # include the latest commit.
          force_orphan: true
          publish_branch: master
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'